# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-GoogleEarth-Pluggable-Plugin-Styles
version:      0.01
version_from: lib/Geo/GoogleEarth/Pluggable/Plugin/Styles.pm
installdirs:  site
requires:
    Geo::GoogleEarth::Pluggable:   0.06
    strict:                        0
    Test::Simple:                  0.44
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
