--- #YAML:1.0
name:               Geo-GoogleEarth-Pluggable-Plugin-Styles
version:            0.02
abstract:           Pre-loaded Styles for Geo::GoogleEarth::Pluggable
author:
    - Michael R. Davis (domain=>michaelrdavis,tld=>com,account=>perl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geo::GoogleEarth::Pluggable:  0.06
    strict:               0
    Test::Simple:         0.44
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
